version: '3.0'

services:
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: unless-stopped

  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload --log-config ../logging.yaml --log-level warning
    volumes:
      - ./app:/opt/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: unless-stopped
